//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nakemu_KütüphanesiEntities : DbContext
    {
        public Nakemu_KütüphanesiEntities()
            : base("name=Nakemu_KütüphanesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanıcı> Kullanıcı { get; set; }
        public virtual DbSet<kitaplar1> kitaplar1 { get; set; }
        public virtual DbSet<odunc> odunc { get; set; }
    }
}
