//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class odunc
    {
        public int IslemID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> IadeTarihi { get; set; }
        public string Durum { get; set; }
    
        public virtual kitaplar1 kitaplar1 { get; set; }
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
